spring:
  liquibase:
    enabled: false

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

#---
#spring.config.activate.on-profile: producer
#server.port: 8001
#
#---
#spring.config.activate.on-profile: consumer-1
#server.port: 8002
#
#---
#spring.config.activate.on-profile: consumer-2
#server.port: 8003
#
#---
