version: '2'

services:

  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    container_name: kafka
    image: debezium/kafka:1.0
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    links:
      - zookeeper
    depends_on:
      - zookeeper

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - 3333:9000
    depends_on:
      - kafka

  postgres:
    container_name: postgres
    image: debezium/example-postgres:1.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres2:
    container_name: postgres2
    image: postgres:13-alpine
    ports:
      - 5401:5432
    environment:
      - POSTGRES_DB=newperf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  debezium:
    container_name: debezium
    image: debezium/connect:1.0
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs   # конфиги коннектора и его задания
      - OFFSET_STORAGE_TOPIC=my_connect_offsets   # позиции, на которых находится коннектор
      - STATUS_STORAGE_TOPIC=my_connect_statuses  # статус коннектора
    depends_on:
      - zookeeper
      - kafka
      - postgres

  jdbc-sink:
    image: confluentinc/cp-kafka-connect
    container_name: kafka-connect-jdbc-sink
    links:
      - zookeeper
      - kafka
      - postgres2
    ports:
      - 28083:8083
    environment:
      - CONNECT_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_REST_PORT=28083
      - CONNECT_GROUP_ID="sink-connect"
      - CONNECT_CONFIG_STORAGE_TOPIC="sink-config"
      - CONNECT_OFFSET_STORAGE_TOPIC="sink-offsets"
      - CONNECT_STATUS_STORAGE_TOPIC="sink-status"
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER="io.confluent.connect.avro.AvroConverter"
      - CONNECT_VALUE_CONVERTER="io.confluent.connect.avro.AvroConverter"
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL="http://localhost:8081"
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL="http://localhost:8081"
      - CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
      - CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
      - CONNECT_REST_ADVERTISED_HOST_NAME="localhost"
      - CONNECT_LOG4J_ROOT_LOGLEVEL=INFO
      - CONNECT_PLUGIN_PATH=/usr/share/java,/etc/kafka-connect/jars
    volumes:
      - /tmp/quickstart/file:/tmp/quickstart
      - /tmp/quickstart/jars:/etc/kafka-connect/jars