version: '3.9'

services:

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka-1:19092,kafka-2:19092,kafka-3:19092
    ports:
      - 3333:9000
    depends_on:
      - kafka-1
#      - kafka-2
#      - kafka-3

  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka-1:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka-1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka-1
      KAFKA_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://:19092,
        LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
        LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://kafka-1:19092,
        LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  kafka-2:
#    image: wurstmeister/kafka:2.12-2.3.0
#    ports:
#      - 9096:9092
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ADVERTISED_PORT: 9096
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#      KAFKA_ADVERTISED_LISTENERS: >-
#        LISTENER_DOCKER_INTERNAL://kafka-2:19092,
#        LISTENER_DOCKER_EXTERNAL://:9096
#      KAFKA_LISTENERS: >-
#        LISTENER_DOCKER_INTERNAL://:19092,
#        LISTENER_DOCKER_EXTERNAL://:9096
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
#        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
#        LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
#    depends_on:
#      - zookeeper
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#
#  kafka-3:
#    image: wurstmeister/kafka:2.12-2.3.0
#    ports:
#      - 9097:9092
#    environment:
#      KAFKA_BROKER_ID: 3
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ADVERTISED_PORT: 9097
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#      KAFKA_ADVERTISED_LISTENERS: >-
#        LISTENER_DOCKER_INTERNAL://kafka-3:19092,
#        LISTENER_DOCKER_EXTERNAL://:9097
#      KAFKA_LISTENERS: >-
#        LISTENER_DOCKER_INTERNAL://:19092,
#        LISTENER_DOCKER_EXTERNAL://:9097
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
#        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
#        LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
#    depends_on:
#      - zookeeper
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock