logging.level.root: ERROR
logging.level.ru.stepanov: DEBUG

spp:
  kafka:
    topic: russian-mail
    group: spp-group
    acks: all
    bootstrapServer: localhost:9095
    sessionTimeoutMillis: 1000
    rebalanceTimeoutMillis: 1000

