spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spp
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog.xml
    user: user
    password: pass

