version: '3.9'

services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: spp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
    ports:
      - 8090:80
